---
- project:
    check:
      jobs:
        - keycloak-extensions-maven-build
        - keycloak-extensions-test-deploy
    gate:
      jobs:
        - keycloak-extensions-maven-build
        - keycloak-extensions-test-deploy
