---
- project:
    check:
      jobs:
        - keycloak-extensions-maven-build:
            vars:
              jdk_version: 17
        - keycloak-extensions-test-deploy-23.0:
            vars:
              jdk_version: 17
        - keycloak-extensions-test-deploy-latest:
            voting: false
    gate:
      jobs:
        - keycloak-extensions-maven-build:
            vars:
              jdk_version: 17
        - keycloak-extensions-test-deploy-23.0:
            vars:
              jdk_version: 17
        - keycloak-extensions-test-deploy-latest:
            voting: false