---
- project:
    check:
      jobs:
        - maven-build
        - keycloak-test-deploy:
            required-projects:
              - software-factory/sf-ci
            dependencies:
              - maven-build
    gate:
      jobs:
        - maven-build
        - keycloak-test-deploy:
            required-projects:
              - software-factory/sf-ci
            dependencies:
              - maven-build
